#!/usr/bin/env bash

com=""
for i in `seq $#`
do
    com=`echo $com ${!i}`
done
$com

unameOS="$(uname -s)"
case "${unameOS}" in
    Linux*)
        notify-send "$1 - completed" "Exit code : $?"
        ;;
    Darwin*)
        osascript -e 'display notification  "Exit code: '"$?"'" with Title "Command \"'"$1"'\" completed"'
        ;;
esac


